services:
  - type: web
    name: rails-api
    env: ruby
    plan: free

    buildCommand: |
      bundle install
      bundle exec rails db:migrate

    startCommand: bundle exec rails server -p 3000 -e production

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: rails-db
    plan: free
